type Car {
  id: ID!
  brand: String!
  year: Int!
  price: Int!
  color: String!
  carTypeId: Int!
}

type Query {
  getCarlist: [Car!]!
  getOneCar(id: Int!): Car!
}

type Mutation {
  createCar(createCarDto: CreateCarDto!): Car!
}

input CreateCarDto {
  brand: String
  price: Int!
  color: String!
  year: Int!
  carTypeId: Int!
}