type CarType {
  id: ID
  name: String
}

input CreateCarTypeInput {
  name: String!
}

input UpdateCarTypeInput {
  id: Int!
  name: String!
}

type Query {
  carTypes: [CarType]!
  carType(id: Int!): CarType
}

type Mutation {
  createCarType(createCarTypeInput: CreateCarTypeInput!): CarType!
  updateCarType(updateCarTypeInput: UpdateCarTypeInput!): CarType!
  removeCarType(id: Int!): CarType
}
